[build]
  # Directory to publish
  publish = "."
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version for functions
  NODE_VERSION = "18"

# Redirect rules (optional)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Environment variables (set these in Netlify dashboard)
# GEMINI_API_KEY = your_gemini_api_key
# NEWS_API_KEY = your_news_api_key